import React from 'react';
import {BrowserRouter,Routes,Route,Navigate} from "react-router-dom";
import Navbar from "./components/layout/Navbar"; import Footer from "./components/layout/Footer"; import MobileBottomNav from "./components/layout/MobileBottomNav"; import Toast from "./components/ui/Toast";
import {useNotifications} from "./contexts/NotificationContext"; import {useAuth} from "./contexts/AuthContext";
import Home from "./pages/public/Home"; import FindRide from "./pages/public/FindRide"; import OfferRide from "./pages/public/OfferRide"; import HowItWorks from "./pages/public/HowItWorks"; import Safety from "./pages/public/Safety"; import About from "./pages/public/About"; import Contact from "./pages/public/Contact";
import Login from "./pages/auth/Login"; import Register from "./pages/auth/Register"; import ForgotPassword from "./pages/auth/ForgotPassword";
import PassengerDashboard from "./pages/passenger/Dashboard"; import Requests from "./pages/passenger/Requests"; import Bookings from "./pages/passenger/Bookings"; import PassengerWallet from "./pages/passenger/Wallet"; import PassengerReviews from "./pages/passenger/Reviews";
import DriverDashboard from "./pages/driver/Dashboard"; import MyRides from "./pages/driver/MyRides"; import DriverRequests from "./pages/driver/Requests"; import Vehicle from "./pages/driver/Vehicle"; import Verification from "./pages/driver/Verification"; import Earnings from "./pages/driver/Earnings"; import DriverReviews from "./pages/driver/Reviews";
import AdminDashboard from "./pages/admin/Dashboard";
import * as Admin from "./pages/admin";
import Terms from "./pages/legal/Terms"; import Privacy from "./pages/legal/Privacy"; import Cancellation from "./pages/legal/Cancellation"; import PaymentPolicy from "./pages/legal/PaymentPolicy";

function Guard({role,children}:{role:"passenger"|"driver"|"admin";children:React.ReactNode}){const {profile}=useAuth();return profile?.role===role?children:<Navigate to="/login" replace/>}
export default function App(){const {notices,remove}=useNotifications();return <BrowserRouter><Navbar/><main className="min-h-[calc(100vh-160px)] pb-16 md:pb-0"><Routes>
<Route path="/" element={<Home/>}/><Route path="/find-ride" element={<FindRide/>}/><Route path="/offer-ride" element={<OfferRide/>}/><Route path="/how-it-works" element={<HowItWorks/>}/><Route path="/safety" element={<Safety/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/>
<Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/>
<Route path="/passenger" element={<Guard role="passenger"><PassengerDashboard/></Guard>}/><Route path="/passenger/requests" element={<Guard role="passenger"><Requests/></Guard>}/><Route path="/passenger/bookings" element={<Guard role="passenger"><Bookings/></Guard>}/><Route path="/passenger/wallet" element={<Guard role="passenger"><PassengerWallet/></Guard>}/><Route path="/passenger/reviews" element={<Guard role="passenger"><PassengerReviews/></Guard>}/>
<Route path="/driver" element={<Guard role="driver"><DriverDashboard/></Guard>}/><Route path="/driver/rides" element={<Guard role="driver"><MyRides/></Guard>}/><Route path="/driver/requests" element={<Guard role="driver"><DriverRequests/></Guard>}/><Route path="/driver/vehicle" element={<Guard role="driver"><Vehicle/></Guard>}/><Route path="/driver/verification" element={<Guard role="driver"><Verification/></Guard>}/><Route path="/driver/earnings" element={<Guard role="driver"><Earnings/></Guard>}/><Route path="/driver/reviews" element={<Guard role="driver"><DriverReviews/></Guard>}/>
<Route path="/admin" element={<Guard role="admin"><AdminDashboard/></Guard>}/>
<Route path="/admin/users" element={<Guard role="admin"><Admin.Users/></Guard>}/><Route path="/admin/drivers" element={<Guard role="admin"><Admin.Drivers/></Guard>}/><Route path="/admin/vehicles" element={<Guard role="admin"><Admin.Vehicles/></Guard>}/><Route path="/admin/rides" element={<Guard role="admin"><Admin.Rides/></Guard>}/><Route path="/admin/bookings" element={<Guard role="admin"><Admin.Bookings/></Guard>}/><Route path="/admin/payments" element={<Guard role="admin"><Admin.Payments/></Guard>}/><Route path="/admin/transactions" element={<Guard role="admin"><Admin.Transactions/></Guard>}/><Route path="/admin/reports" element={<Guard role="admin"><Admin.Reports/></Guard>}/><Route path="/admin/reviews" element={<Guard role="admin"><Admin.Reviews/></Guard>}/><Route path="/admin/settings" element={<Guard role="admin"><Admin.Settings/></Guard>}/><Route path="/admin/audit-logs" element={<Guard role="admin"><Admin.AuditLogs/></Guard>}/>
<Route path="/legal/terms" element={<Terms/>}/><Route path="/legal/privacy" element={<Privacy/>}/><Route path="/legal/cancellation" element={<Cancellation/>}/><Route path="/legal/payment-policy" element={<PaymentPolicy/>}/>
<Route path="*" element={<Navigate to="/" replace/>}/>
</Routes></main><Footer/><MobileBottomNav/><div className="fixed right-4 top-20 z-50 w-[min(92vw,380px)] space-y-2">{notices.map(n=><Toast key={n.id} type={n.type} message={n.message} onClose={()=>remove(n.id)}/>)}</div></BrowserRouter>}
